services:
  gateway:
    build:
      context: .
      dockerfile: src/Services/Gateway/Gateway.Api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_URLS=http://+:8000
      - SERVICE_NAME=gateway
      - PORT=8000
      - ServiceMap__auth=http://auth:8001
      - ServiceMap__catalog=http://catalog:8002
      - ServiceMap__basket=http://basket:8006
      - ServiceMap__order=http://order:8003
      - ServiceMap__inventory=http://inventory:8004
      - ServiceMap__notification=http://notification:8005
    depends_on:
      - auth
      - catalog
      - basket
      - order
      - inventory
      - notification

  auth:
    build:
      context: .
      dockerfile: src/Services/Auth/Auth.Api/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ASPNETCORE_URLS=http://+:8001
      - SERVICE_NAME=auth
      - PORT=8001
      - ConnectionStrings__AuthDb=Host=postgres;Port=5432;Database=auth_db;Username=postgres;Password=postgres
      - Jwt__Issuer=OpsFlow.Auth.Docker
      - Jwt__Audience=OpsFlow.Api.Docker
      - Jwt__SigningKey=dev-only-change-this-key-before-production-opsflow-2026
      - Jwt__AccessTokenMinutes=60
    depends_on:
      postgres:
        condition: service_healthy

  catalog:
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.Api/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - ASPNETCORE_URLS=http://+:8002
      - SERVICE_NAME=catalog
      - PORT=8002
      - ConnectionStrings__CatalogDb=Host=postgres;Port=5432;Database=catalog_db;Username=postgres;Password=postgres
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    depends_on:
      - postgres
      - redis
      - rabbitmq

  basket:
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.Api/Dockerfile
    ports:
      - "8006:8006"
    environment:
      - ASPNETCORE_URLS=http://+:8006
      - SERVICE_NAME=basket
      - PORT=8006
      - ConnectionStrings__Redis=redis:6379
      - CatalogApi__Url=http://catalog:8002/
      - InventoryGrpc__Url=http://inventory:8007
      - Jwt__Issuer=OpsFlow.Auth.Docker
      - Jwt__Audience=OpsFlow.Api.Docker
      - Jwt__SigningKey=dev-only-change-this-key-before-production-opsflow-2026
    depends_on:
      - redis
      - inventory

  order:
    build:
      context: .
      dockerfile: src/Services/Order/Order.Api/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - ASPNETCORE_URLS=http://+:8003
      - SERVICE_NAME=order
      - PORT=8003
      - ConnectionStrings__OrderDb=Host=postgres;Port=5432;Database=order_db;Username=postgres;Password=postgres
      - Jwt__Issuer=OpsFlow.Auth.Docker
      - Jwt__Audience=OpsFlow.Api.Docker
      - Jwt__SigningKey=dev-only-change-this-key-before-production-opsflow-2026
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    depends_on:
      - postgres
      - rabbitmq

  inventory:
    build:
      context: .
      dockerfile: src/Services/Inventory/Inventory.Api/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - ASPNETCORE_URLS=http://+:8004
      - SERVICE_NAME=inventory
      - PORT=8004
      - ConnectionStrings__InventoryDb=Host=postgres;Port=5432;Database=inventory_db;Username=postgres;Password=postgres
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    depends_on:
      - postgres
      - redis
      - rabbitmq

  notification:
    build:
      context: .
      dockerfile: src/Services/Notification/Notification.Api/Dockerfile
    ports:
      - "8005:8005"
    environment:
      - ASPNETCORE_URLS=http://+:8005
      - SERVICE_NAME=notification
      - PORT=8005
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - MongoDb__ConnectionString=mongodb://mongo:27017
      - MongoDb__Database=notification_db
      - MongoDb__Collection=notifications
      - Jwt__Issuer=OpsFlow.Auth.Docker
      - Jwt__Audience=OpsFlow.Api.Docker
      - Jwt__SigningKey=dev-only-change-this-key-before-production-opsflow-2026
    depends_on:
      - rabbitmq
      - mongo

  frontend:
    build:
      context: ./frontend/opsflow-web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_SIGNALR_URL=http://localhost:8000/signalr/live
    depends_on:
      - gateway

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

volumes:
  postgres_data:
