import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: theme.spacing.lg,
    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: 'hidden',
    gap: 16,
  },
  header: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  pulse: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: theme.colors.success,
    borderWidth: 4,
    borderColor: '#D8F4E5',
  },
  headerText: { flex: 1, gap: 3 },
  title: { color: theme.colors.text, fontSize: 16, fontWeight: '900' },
  status: { color: theme.colors.primaryDark, fontSize: 17, lineHeight: 22, fontWeight: '800' },
  orderNumber: { color: theme.colors.muted, fontSize: 11, fontWeight: '700', marginTop: 2 },
  items: { gap: 8, paddingTop: 12, borderTopWidth: 1, borderTopColor: theme.colors.border },
  itemRow: { flexDirection: 'row', alignItems: 'flex-start' },
  itemText: { flex: 1, gap: 2 },
  itemName: { color: theme.colors.text, fontSize: 14, fontWeight: '800' },
  itemOptions: { color: theme.colors.muted, fontSize: 12, lineHeight: 17 },
  timeline: { flexDirection: 'row', alignItems: 'flex-start' },
  timelineStep: { flex: 1, alignItems: 'center', position: 'relative' },
  timelineDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceSoft,
    borderWidth: 1,
    borderColor: theme.colors.border,
    zIndex: 1,
  },
  timelineDotActive: { backgroundColor: theme.colors.success, borderColor: theme.colors.success },
  timelineCheck: { color: theme.colors.muted, fontSize: 13, fontWeight: '900' },
  timelineCheckActive: { color: '#fff' },
  timelineLabel: {
    color: theme.colors.muted,
    fontSize: 9,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 6,
  },
  timelineLabelActive: { color: theme.colors.primaryDark },
  timelineLine: {
    position: 'absolute',
    top: 11,
    left: '50%',
    right: '-50%',
    height: 2,
    backgroundColor: theme.colors.border,
  },
  timelineLineActive: { backgroundColor: theme.colors.success },
});
