// <auto-generated />
using System;
using Order.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Order.Api.Infrastructure.Persistence.Migrations;

[DbContext(typeof(OrderDbContext))]
partial class OrderDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.9")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("Order.Api.Domain.Order", b =>
        {
            b.Property<string>("Id")
                .ValueGeneratedNever()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<string>("CustomerId")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Note")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("billing_city")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("character varying(150)");

            b.Property<string>("billing_country")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<string>("billing_district")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("character varying(150)");

            b.Property<string>("billing_postal_code")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("billing_street")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.Property<string>("shipping_city")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("character varying(150)");

            b.Property<string>("shipping_country")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<string>("shipping_district")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("character varying(150)");

            b.Property<string>("shipping_postal_code")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("shipping_street")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.Property<int>("Status")
                .HasColumnType("integer");

            b.Property<DateTimeOffset?>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("payment_method")
                .HasColumnType("integer");

            b.Property<int>("payment_status")
                .HasColumnType("integer");

            b.HasKey("Id");

            b.ToTable("orders");

            b.OwnsMany("Order.Api.Domain.OrderItem", "Items", b1 =>
            {
                b1.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                b1.Property<string>("OrderId")
                    .IsRequired()
                    .HasColumnType("character varying(32)");

                b1.Property<string>("ProductId")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b1.Property<int>("Quantity")
                    .HasColumnType("integer");

                b1.Property<string>("SelectedOptionIdsJson")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("character varying(4000)");

                b1.HasKey("Id");

                b1.HasIndex("OrderId");

                b1.ToTable("order_items");
            });

            b.Navigation("Items");
        });

        modelBuilder.Entity("Order.Api.Infrastructure.Outbox.OutboxMessage", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<string>("Error")
                .HasMaxLength(2000)
                .HasColumnType("character varying(2000)");

            b.Property<DateTimeOffset?>("FailedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset?>("LockedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset>("OccurredAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset?>("ProcessingAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Payload")
                .IsRequired()
                .HasColumnType("text");

            b.Property<DateTimeOffset?>("ProcessedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("RetryCount")
                .HasColumnType("integer");

            b.Property<string>("Type")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.HasKey("Id");

            b.HasIndex("FailedAt");

            b.HasIndex("LockedAt");

            b.HasIndex("OccurredAt");

            b.HasIndex("ProcessedAt");

            b.ToTable("outbox_messages");
        });

        modelBuilder.Entity("Order.Api.Domain.Order", b =>
        {
            b.OwnsOne("Order.Api.Domain.Address", "BillingAddress", b1 =>
            {
                b1.Property<string>("Order.Api.Domain.OrderId")
                    .HasColumnType("character varying(32)");

                b1.Property<string>("Country")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("billing_country");

                b1.Property<string>("City")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("billing_city");

                b1.Property<string>("District")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("billing_district");

                b1.Property<string>("PostalCode")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("billing_postal_code");

                b1.Property<string>("Street")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("character varying(250)")
                    .HasColumnName("billing_street");

                b1.HasKey("Order.Api.Domain.OrderId");

                b1.ToTable("orders");
            });

            b.OwnsOne("Order.Api.Domain.Address", "ShippingAddress", b1 =>
            {
                b1.Property<string>("Order.Api.Domain.OrderId")
                    .HasColumnType("character varying(32)");

                b1.Property<string>("Country")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("shipping_country");

                b1.Property<string>("City")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("shipping_city");

                b1.Property<string>("District")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("shipping_district");

                b1.Property<string>("PostalCode")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("shipping_postal_code");

                b1.Property<string>("Street")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("character varying(250)")
                    .HasColumnName("shipping_street");

                b1.HasKey("Order.Api.Domain.OrderId");

                b1.ToTable("orders");
            });

            b.OwnsOne("Order.Api.Domain.Payment", "Payment", b1 =>
            {
                b1.Property<string>("Order.Api.Domain.OrderId")
                    .HasColumnType("character varying(32)");

                b1.Property<int>("Method")
                    .HasColumnName("payment_method")
                    .HasColumnType("integer");

                b1.Property<int>("Status")
                    .HasColumnName("payment_status")
                    .HasColumnType("integer");

                b1.HasKey("Order.Api.Domain.OrderId");

                b1.ToTable("orders");
            });

            b.Navigation("BillingAddress");
            b.Navigation("Payment");
            b.Navigation("ShippingAddress");
        });
    }
}
