import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    minHeight: 0,
    backgroundColor: theme.colors.background,
  },
  scroll: { flex: 1, minHeight: 0 },
  content: {
    paddingBottom: 28,
    gap: 12,
  },
  stepsCard: {
    backgroundColor: theme.colors.surface,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  step: {
    alignItems: 'center',
    flex: 1,
    gap: 4,
  },
  stepActive: {
    alignItems: 'center',
    flex: 1,
    gap: 4,
  },
  stepIcon: {
    color: theme.colors.muted,
    fontSize: 19,
  },
  stepActiveText: {
    color: theme.colors.primary,
    fontWeight: '900',
    fontSize: 12,
  },
  stepText: {
    color: theme.colors.muted,
    fontWeight: '700',
    fontSize: 11,
    textAlign: 'center',
  },
  stepArrow: {
    color: theme.colors.border,
    fontSize: 28,
    lineHeight: 30,
  },
  banner: {
    width: '100%',
    height: 116,
    backgroundColor: theme.colors.surfaceSoft,
  },
  itemsCard: {
    marginHorizontal: 16,
    backgroundColor: theme.colors.surface,
    borderRadius: 18,
    overflow: 'hidden',
  },
  itemRow: {
    paddingHorizontal: 18,
    paddingVertical: 22,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    gap: 10,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  itemTitle: {
    flex: 1,
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: '700',
  },
  itemPrice: {
    color: '#e3b341',
    fontSize: 16,
    fontWeight: '900',
  },
  itemMeta: {
    color: theme.colors.muted,
    fontSize: 13,
  },
  itemActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  quantityControl: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 24,
    overflow: 'hidden',
  },
  quantityButton: {
    width: 48,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonText: {
    color: theme.colors.text,
    fontSize: 23,
  },
  quantityValue: {
    minWidth: 50,
    height: 46,
    textAlign: 'center',
    textAlignVertical: 'center',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: theme.colors.border,
    color: theme.colors.primary,
    fontSize: 21,
    fontWeight: '900',
  },
  deleteButton: {
    padding: 10,
  },
  deleteIcon: {
    color: theme.colors.primary,
    fontSize: 25,
  },
  promoCard: {
    marginHorizontal: 16,
    borderRadius: 16,
    backgroundColor: '#0d1f0d',
    paddingHorizontal: 16,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  promoIcon: {
    fontSize: 20,
  },
  promoText: {
    flex: 1,
    color: '#3fb950',
    fontWeight: '700',
    fontSize: 13,
  },
  checkoutBar: {
    marginHorizontal: 16,
    padding: 16,
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  checkoutLabel: {
    color: theme.colors.muted,
    fontWeight: '700',
    fontSize: 12,
  },
  checkoutTotal: {
    color: '#e3b341',
    fontSize: 24,
    fontWeight: '900',
  },
  checkoutButton: {
    flex: 1,
    backgroundColor: theme.colors.success,
    borderRadius: 28,
    paddingVertical: 16,
    alignItems: 'center',
  },
  checkoutButtonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '900',
  },
});
